export const productos = [
    {
        id: 1,
        name: 'Quilmes',
        image: 'quilmes',
        price: 180,
        category: 'cervezas',
    }, {
        id: 2,
        name: 'Quilmes Lata',
        image: 'quilmes-lata',
        price: 120,
        category: 'cervezas',
    }, {
        id: 3,
        name: 'Brahma',
        image: 'brahma',
        price: 190,
        category: 'cervezas',
    }, {
        id: 4,
        name: 'Fernet Branca',
        image: 'fernet-branca',
        price: 720,
        category: 'aperitivos',
    }, {
        id: 5,
        name: 'fernet 1882',
        image: 'fernet-1882',
        price: 550,
        category: 'aperitivos',
    }, {
        id: 6,
        name: 'Corona',
        image: 'corona',
        price: 230,
        category: 'cervezas',
    }, {
        id: 7,
        name: 'Speed 473',
        image: 'speed-473',
        price: 150,
        category: 'energizantes',
    }, {
        id: 8,
        name: 'Speed 250',
        image: 'speed-250',
        price: 80,
        category: 'energizantes',
    }, {
        id: 9,
        name: 'Moster Mango Loco',
        image: 'monster-3',
        price: 170,
        category: 'energizantes',
    }, {
        id: 10,
        name: 'Moster Ultra Sunrise',
        image: 'monster-4',
        price: 170,
        category: 'energizantes',
    }, {
        id: 11,
        name: 'Moster Ultra Paradice',
        image: 'monster-2',
        price: 170,
        category: 'energizantes',
    }, {
        id: 12,
        name: 'Monster',
        image: 'monster-1',
        price: 170,
        category: 'energizantes',
    }, {
        id: 13,
        name: 'Sernova',
        image: 'sernova',
        price: 550,
        category: 'vodkas',
    }, {
        id: 14,
        name: 'Smirnoff',
        image: 'smirnoff',
        price: 600,
        category: 'vodkas',
    }, {
        id: 15,
        name: 'Smirnoff Ice',
        image: 'smirnoff-ice',
        price: 170,
        category: 'vodkas',
    }, {
        id: 16,
        name: 'Smirnoff Apple',
        image: 'smirnoff-apple',
        price: 170,
        category: 'vodkas',
    }, {
        id: 17,
        name: 'Schneider 710',
        image: 'schneider-710',
        price: 150,
        category: 'cervezas',
    }, {
        id: 18,
        name: 'Patagonia Kuné',
        image: 'patagonia-kune-730',
        price: 190,
        category: 'cervezas',
    }, {
        id: 19,
        name: 'Baggio Multifruta',
        image: 'multifruta-grande',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 20,
        name: 'Baggio Naranja',
        image: 'naranja-grande',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 21,
        name: 'Manaos Naranja',
        image: 'naranja',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 22,
        name: 'Manaos Pomelo',
        image: 'pomelo',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 23,
        name: 'Manaos Cola',
        image: 'cola',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 24,
        name: 'Manaos Lima',
        image: 'lima',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 25,
        name: 'Master',
        image: 'master',
        price: 190,
        category: 'cigarillos',
    }, {
        id: 26,
        name: 'Red Point',
        image: 'red-point',
        price: 190,
        category: 'cigarillos',
    }

]