export const productos = [
    {
        id: 1,
        name: 'Quilmes',
        image: 'quilmes.jpeg',
        price: 180,
        category: 'cervezas',
    }, {
        id: 2,
        name: 'Quilmes Lata',
        image: 'quilmes-lata.jpeg',
        price: 120,
        category: 'cervezas',
    }, {
        id: 3,
        name: 'Brahma',
        image: 'brahma.jpeg',
        price: 190,
        category: 'cervezas',
    }, {
        id: 4,
        name: 'Fernet Branca',
        image: 'fernet-branca.jpeg',
        price: 720,
        category: 'aperitivos',
    }, {
        id: 5,
        name: 'fernet 1882',
        image: 'fernet-1882.jpeg',
        price: 550,
        category: 'aperitivos',
    }, {
        id: 6,
        name: 'Corona',
        image: 'corona.jpeg',
        price: 230,
        category: 'cervezas',
    }, {
        id: 7,
        name: 'Speed 473',
        image: 'speed-473.jpeg',
        price: 150,
        category: 'energizantes',
    }, {
        id: 8,
        name: 'Speed 250',
        image: 'speed-250.jpeg',
        price: 80,
        category: 'energizantes',
    }, {
        id: 9,
        name: 'Moster Mango Loco',
        image: 'monster-3.jpeg',
        price: 170,
        category: 'energizantes',
    }, {
        id: 10,
        name: 'Moster Ultra Sunrise',
        image: 'monster-4.jpeg',
        price: 170,
        category: 'energizantes',
    }, {
        id: 11,
        name: 'Moster Ultra Paradice',
        image: 'monster-2.jpeg',
        price: 170,
        category: 'energizantes',
    }, {
        id: 12,
        name: 'Monster',
        image: 'monster-1.jpeg',
        price: 170,
        category: 'energizantes',
    }, {
        id: 13,
        name: 'Sernova',
        image: 'sernova.jpeg',
        price: 550,
        category: 'vodkas',
    }, {
        id: 14,
        name: 'Smirnoff',
        image: 'smirnoff.jpeg',
        price: 600,
        category: 'vodkas',
    }, {
        id: 15,
        name: 'Smirnoff Ice',
        image: 'smirnoff-ice.jpeg',
        price: 170,
        category: 'vodkas',
    }, {
        id: 16,
        name: 'Smirnoff Apple',
        image: 'smirnoff-apple.jpeg',
        price: 170,
        category: 'vodkas',
    }, {
        id: 17,
        name: 'Schneider 710',
        image: 'schneider-710.jpeg',
        price: 150,
        category: 'cervezas',
    }, {
        id: 18,
        name: 'Patagonia Kuné',
        image: 'patagonia-kune-730.jpeg',
        price: 190,
        category: 'cervezas',
    }, {
        id: 19,
        name: 'Baggio Multifruta',
        image: 'multifruta-grande.jpeg',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 20,
        name: 'Baggio Naranja',
        image: 'naranja-grande.jpeg',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 21,
        name: 'Manaos Naranja',
        image: 'naranja.jpeg',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 22,
        name: 'Manaos Pomelo',
        image: 'pomelo.jpeg',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 23,
        name: 'Manaos Cola',
        image: 'cola.jpeg',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 24,
        name: 'Manaos Lima',
        image: 'lima.jpeg',
        price: 190,
        category: 'gaseosa/jugos',
    }, {
        id: 25,
        name: 'Master',
        image: 'master.jpeg',
        price: 190,
        category: 'cigarillos',
    }, {
        id: 26,
        name: 'Red Point',
        image: 'red-point.jpeg',
        price: 190,
        category: 'cigarillos',
    }

]